"""Feature registry for stylometry metadata."""

from __future__ import annotations

import re
from dataclasses import dataclass

from stylometry_python_lib.specs import (
    FeatureImplementationStatus,
    FeatureOutputMode,
    FeatureSpec,
    InputLayer,
    ResearchBucket,
    ResearchFeatureEntry,
    TopicDependence,
    validate_feature_spec,
    validate_research_feature_entry,
)


@dataclass(frozen=True)
class FeatureRegistry:
    """Immutable registry snapshot for feature metadata."""

    specs: tuple[FeatureSpec, ...]

    def names(self) -> tuple[str, ...]:
        """Return registered feature names in order."""
        return tuple(spec.name for spec in self.specs)

    def require_complete(self) -> None:
        """Validate all registered feature specs."""
        seen: set[str] = set()
        for spec in self.specs:
            validate_feature_spec(spec)
            if spec.name in seen:
                raise ValueError(f"Duplicate feature name registered: {spec.name}")
            seen.add(spec.name)

    def by_name(self, name: str) -> FeatureSpec:
        """Return one feature spec by name."""
        for spec in self.specs:
            if spec.name == name:
                return spec
        raise KeyError(f"Unknown feature spec: {name}")


@dataclass(frozen=True)
class AvailabilityCounts:
    """Machine-readable feature accounting counts for the research registry."""

    planned_research_families: int
    implemented_feature_blocks: int
    emitted_numeric_columns: int
    sidecar_annotation_types: int
    catalog_only_unavailable_entries: int
    out_of_scope_entries: int


@dataclass(frozen=True)
class ResearchFeatureRegistry:
    """Immutable registry manifest covering all research rows."""

    entries: tuple[ResearchFeatureEntry, ...]

    def require_complete(self) -> None:
        """Validate all research registry entries."""
        seen_taxonomy_ids: set[str] = set()
        seen_block_ids: set[str] = set()
        for entry in self.entries:
            validate_research_feature_entry(entry)
            if entry.taxonomy_id in seen_taxonomy_ids:
                raise ValueError(f"Duplicate research taxonomy id registered: {entry.taxonomy_id}")
            if entry.block_id in seen_block_ids:
                raise ValueError(f"Duplicate research block id registered: {entry.block_id}")
            seen_taxonomy_ids.add(entry.taxonomy_id)
            seen_block_ids.add(entry.block_id)

    def by_taxonomy_id(self, taxonomy_id: str) -> ResearchFeatureEntry:
        """Return one research entry by stable taxonomy id."""
        for entry in self.entries:
            if entry.taxonomy_id == taxonomy_id:
                return entry
        raise KeyError(f"Unknown research taxonomy id: {taxonomy_id}")

    def select_by_taxonomy_ids(self, taxonomy_ids: tuple[str, ...]) -> tuple[ResearchFeatureEntry, ...]:
        """Select entries by stable taxonomy ids while preserving requested order."""
        return tuple(self.by_taxonomy_id(taxonomy_id) for taxonomy_id in taxonomy_ids)

    def select_by_block_id(self, block_id: str) -> ResearchFeatureEntry:
        """Select one entry by stable block id."""
        for entry in self.entries:
            if entry.block_id == block_id:
                return entry
        raise KeyError(f"Unknown research block id: {block_id}")

    def select_by_output_name_regex(self, pattern: str) -> tuple[ResearchFeatureEntry, ...]:
        """Select entries whose machine-readable output pattern matches a regex."""
        compiled = re.compile(pattern)
        return tuple(entry for entry in self.entries if compiled.search(entry.output_name_pattern) is not None)

    def select_by_feature_spec(self, spec: FeatureSpec) -> ResearchFeatureEntry:
        """Select the research row that owns a concrete emitted feature spec."""
        for entry in self.entries:
            if spec.name.startswith(entry.output_name_pattern.removesuffix("*")):
                return entry
        raise KeyError(f"No research registry entry owns feature spec: {spec.name}")

    def availability_counts(self) -> AvailabilityCounts:
        """Report separate counts for family, block, column, sidecar, and unavailable accounting."""
        implemented_statuses = {FeatureImplementationStatus.IMPLEMENTED, FeatureImplementationStatus.PARTIAL}
        unavailable_statuses = {
            FeatureImplementationStatus.CATALOG_ONLY,
            FeatureImplementationStatus.BLOCKED_BY_PROVIDER,
            FeatureImplementationStatus.BLOCKED_BY_EXTERNAL_DECISION,
        }
        return AvailabilityCounts(
            planned_research_families=len(self.entries),
            implemented_feature_blocks=sum(1 for entry in self.entries if entry.status in implemented_statuses),
            emitted_numeric_columns=sum(entry.emitted_numeric_columns for entry in self.entries),
            sidecar_annotation_types=sum(1 for entry in self.entries if entry.sidecar_schema != "none"),
            catalog_only_unavailable_entries=sum(1 for entry in self.entries if entry.status in unavailable_statuses),
            out_of_scope_entries=sum(1 for entry in self.entries if entry.status == FeatureImplementationStatus.OUT_OF_SCOPE),
        )

    def availability_matrix(self) -> tuple[dict[str, str | int], ...]:
        """Return a stable machine-readable availability matrix."""
        return tuple(
            {
                "taxonomy_id": entry.taxonomy_id,
                "bucket": entry.bucket.value,
                "family_id": entry.family_id,
                "block_id": entry.block_id,
                "output_name_pattern": entry.output_name_pattern,
                "status": entry.status.value,
                "topic_dependence": entry.topic_dependence.value,
                "input_layer": entry.input_layer.value,
                "output_mode": entry.output_mode.value,
                "dependency_extra": entry.dependency_extra,
                "implementation_owner": entry.implementation_owner,
                "test_status": entry.test_status,
                "emitted_numeric_columns": entry.emitted_numeric_columns,
                "sidecar_schema": entry.sidecar_schema,
            }
            for entry in self.entries
        )


def built_in_research_registry() -> ResearchFeatureRegistry:
    """Return the built-in research-family registry from docs/RESEARCH.md."""
    registry = ResearchFeatureRegistry(entries=_DETERMINISTIC_ENTRIES + _OTHER_NON_LLM_ENTRIES + _LLM_ENTRIES)
    registry.require_complete()
    return registry


def _entry(
    taxonomy_id: str,
    bucket: ResearchBucket,
    family_id: str,
    block_id: str,
    output_name_pattern: str,
    status: FeatureImplementationStatus,
    formula_or_rule: str,
    input_layer: InputLayer,
    topic_dependence: TopicDependence,
    text_length_policy: str,
    undefined_behavior: str,
    provenance_requirements: str,
    output_dtype: str,
    output_shape: str,
    output_mode: FeatureOutputMode,
    dependency_extra: str,
    implementation_owner: str,
    test_status: str,
    documentation_link: str,
    emitted_numeric_columns: int,
    sidecar_schema: str,
) -> ResearchFeatureEntry:
    return ResearchFeatureEntry(
        taxonomy_id=taxonomy_id,
        bucket=bucket,
        family_id=family_id,
        block_id=block_id,
        output_name_pattern=output_name_pattern,
        status=status,
        formula_or_rule=formula_or_rule,
        input_layer=input_layer,
        topic_dependence=topic_dependence,
        text_length_policy=text_length_policy,
        undefined_behavior=undefined_behavior,
        provenance_requirements=provenance_requirements,
        output_dtype=output_dtype,
        output_shape=output_shape,
        output_mode=output_mode,
        dependency_extra=dependency_extra,
        implementation_owner=implementation_owner,
        test_status=test_status,
        documentation_link=documentation_link,
        emitted_numeric_columns=emitted_numeric_columns,
        sidecar_schema=sidecar_schema,
    )


def _deterministic_entry(
    taxonomy_id: str,
    family_id: str,
    block_id: str,
    output_name_pattern: str,
    status: FeatureImplementationStatus,
    formula_or_rule: str,
    input_layer: InputLayer,
    topic_dependence: TopicDependence,
    text_length_policy: str,
    output_shape: str,
    output_mode: FeatureOutputMode,
    emitted_numeric_columns: int,
    test_status: str,
    sidecar_schema: str,
) -> ResearchFeatureEntry:
    return _entry(
        taxonomy_id,
        ResearchBucket.DETERMINISTIC,
        family_id,
        block_id,
        output_name_pattern,
        status,
        formula_or_rule,
        input_layer,
        topic_dependence,
        text_length_policy,
        "NaN for undefined continuous values; zero only for absent counts with an existing denominator",
        "built-in deterministic rules; explicit preprocessing config; versioned resources when applicable",
        "float64",
        output_shape,
        output_mode,
        "core",
        "stylometry_python_lib.features",
        test_status,
        _deterministic_documentation_link(block_id),
        emitted_numeric_columns,
        sidecar_schema,
    )


def _deterministic_documentation_link(block_id: str) -> str:
    lexical_richness_blocks = {
        "lexical_richness_ttr",
        "lexical_richness_variants",
        "lexical_richness_hapax",
        "lexical_richness_frequency_spectrum",
        "lexical_richness_yules_k",
        "lexical_richness_honore_r",
        "lexical_richness_guiraud_r",
        "lexical_richness_sichel_simpson_renyi",
    }
    if block_id in lexical_richness_blocks:
        return "docs/formulas/lexical-richness.md"
    if block_id == "readability":
        return "docs/formulas/readability.md"
    return "docs/RESEARCH.md#deterministic-methods"


def _other_entry(
    taxonomy_id: str,
    family_id: str,
    block_id: str,
    output_name_pattern: str,
    status: FeatureImplementationStatus,
    formula_or_rule: str,
    input_layer: InputLayer,
    topic_dependence: TopicDependence,
    text_length_policy: str,
    output_shape: str,
    output_mode: FeatureOutputMode,
    dependency_extra: str,
    implementation_owner: str,
    test_status: str,
    emitted_numeric_columns: int,
    sidecar_schema: str,
) -> ResearchFeatureEntry:
    return _entry(
        taxonomy_id,
        ResearchBucket.OTHER_NON_LLM,
        family_id,
        block_id,
        output_name_pattern,
        status,
        formula_or_rule,
        input_layer,
        topic_dependence,
        text_length_policy,
        "fail fast for missing optional dependencies or invalid labels; NaN/diagnostics for undefined numerical outputs",
        "provider/model/version metadata for parser-backed features; split and label metadata for evaluation utilities",
        "float64",
        output_shape,
        output_mode,
        dependency_extra,
        implementation_owner,
        test_status,
        "docs/RESEARCH.md#other-non-llm-methods",
        emitted_numeric_columns,
        sidecar_schema,
    )


def _llm_entry(
    taxonomy_id: str,
    family_id: str,
    block_id: str,
    output_name_pattern: str,
    formula_or_rule: str,
    topic_dependence: TopicDependence,
    output_shape: str,
    output_mode: FeatureOutputMode,
    sidecar_schema: str,
) -> ResearchFeatureEntry:
    return _entry(
        taxonomy_id,
        ResearchBucket.LLM,
        family_id,
        block_id,
        output_name_pattern,
        FeatureImplementationStatus.PARTIAL,
        formula_or_rule,
        InputLayer.LLM,
        topic_dependence,
        "requires prompt-specific context length, provider availability, and stability audit",
        "provider/configuration errors fail fast; invalid JSON/schema/refusal/timeout/truncation become explicit diagnostics",
        "provider; model; model version; prompt version; schema; decoding settings; preprocessing settings; raw response reference",
        "float64_or_structured",
        output_shape,
        output_mode,
        "fake-provider; configured OpenAI-compatible/LM Studio provider; endpoint capability diagnostics for embeddings",
        "stylometry_python_lib.features.optional; stylometry_python_lib.llm; stylometry_python_lib.llm_transformers",
        (
            "fake-provider, prompt/schema, diagnostics, configured LM Studio row/pair, embedding capability, "
            "and recorded/replay offline tests present; live-provider credential opt-in tests pending"
        ),
        "docs/RESEARCH.md#llm-based-methods",
        1,
        sidecar_schema,
    )


_DETERMINISTIC_ENTRIES = (
    _deterministic_entry(
        "det.function_word_frequencies",
        "function_word_frequencies",
        "function_word_frequency",
        "text::function_word*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count fixed function-word list and versioned function-word groups; normalize by total tokens or per 1,000 tokens",
        InputLayer.TOKENS,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "legacy ratios and raw counts are defined when token layer exists; per-1,000-token rates are undefined when token count is zero",
        "fixed dense vector",
        FeatureOutputMode.DENSE_VECTOR,
        107,
        "per-item ratio, per-item count/rate, grouped count/rate, metadata, undefined, output-mode, and serialization tests present",
        "none",
    ),
    _deterministic_entry(
        "det.most_frequent_words",
        "most_frequent_words",
        "most_frequent_words",
        "text::most_frequent_words::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "fit corpus top-k word forms with deterministic count/name ordering",
        InputLayer.TOKENS,
        TopicDependence.TOPIC_SENSITIVE,
        "defined after fit when fitted vocabulary is non-empty",
        "fitted dense or sparse vector",
        FeatureOutputMode.DENSE_VECTOR,
        0,
        "fitted golden, row-preservation, output-mode, and metadata tests present",
        "none",
    ),
    _deterministic_entry(
        "det.word_unigrams",
        "word_unigrams",
        "word_unigram",
        "text::word_ngram::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "sliding token n-grams with ngram_range including one",
        InputLayer.TOKENS,
        TopicDependence.TOPIC_SENSITIVE,
        "defined after fit; absent fitted grams are valid zeros",
        "fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        0,
        "ngram golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.word_ngrams",
        "word_ngrams",
        "word_ngram",
        "text::word_ngram::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "sliding token n-grams with deterministic fitted vocabulary",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "defined after fit; absent fitted grams are valid zeros",
        "fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        0,
        "ngram golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.function_word_ngrams",
        "function_word_ngrams",
        "function_word_ngram",
        "text::function_word_ngram::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "filter to function words, then emit fitted token n-gram counts",
        InputLayer.TOKENS,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "defined after fit; absent fitted grams are valid zeros",
        "fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        0,
        "ngram golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.character_ngrams",
        "character_ngrams",
        "char_ngram",
        "text::char_ngram::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "sliding character n-grams over raw text",
        InputLayer.RAW,
        TopicDependence.MIXED,
        "defined after fit; absent fitted grams are valid zeros",
        "fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        0,
        "ngram golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.special_token_profile",
        "special_token_profile",
        "special_token_profile",
        "text::special_token_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count retained special-token spans, class-normalized spans, and per-orthographic-token rates",
        InputLayer.ORTHOGRAPHIC_TOKENS,
        TopicDependence.MIXED,
        "counts are always defined; rates are NaN when orthographic-token denominator is zero",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        24,
        "golden counts, class-normalized masking, undefined diagnostics, output modes, and serialization tests present",
        "none",
    ),
    _deterministic_entry(
        "det.letter_character_frequencies",
        "letter_character_frequencies",
        "orthography_profile",
        "text::orthography_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        (
            "count Unicode codepoints, Unicode categories, character classes, expanded script inventories, and lowercase Latin "
            "letters with alphabetic and all-character normalization"
        ),
        InputLayer.RAW,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "NaN when alphabetic or character denominators are zero; raw counts are valid zeroes",
        "fixed dense vector plus legacy lowercase letter frequency vector and raw-codepoint sidecar",
        FeatureOutputMode.DENSE_VECTOR,
        209,
        "letter, category, character-class, expanded-script, raw-codepoint, sidecar, and normalization golden tests present",
        "orthography_codepoint_sidecar_v1",
    ),
    _deterministic_entry(
        "det.word_length_statistics",
        "word_length_statistics",
        "length_word",
        "text::length::word_*",
        FeatureImplementationStatus.IMPLEMENTED,
        "mean, median, standard deviation, and extended distribution statistics for token character lengths",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        17,
        "scalar and extended distribution-stat golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.syllable_distribution",
        "syllable_distribution",
        "length_syllables",
        "text::length::syllables_per_word_*",
        FeatureImplementationStatus.IMPLEMENTED,
        "hybrid dictionary-backed syllable counts with heuristic fallback and optional pronunciation sidecars",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "fixed scalar set, distribution-stat block, versioned syllable-count resource, and versioned pronunciation resource",
        FeatureOutputMode.SCALAR,
        15,
        "aggregate, dictionary-hit, heuristic fallback, extended distribution-stat, and pronunciation-sidecar golden tests present",
        "pronunciation_record_v1",
    ),
    _deterministic_entry(
        "det.sentence_length_statistics",
        "sentence_length_statistics",
        "length_sentence_tokens",
        "text::length::sentence_tokens_*",
        FeatureImplementationStatus.IMPLEMENTED,
        "sentence token, character, and heuristic syllable length summary statistics",
        InputLayer.SENTENCES,
        TopicDependence.MIXED,
        "NaN when sentence denominator is zero",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        44,
        "token, character, and syllable extended distribution-stat golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.paragraph_length_statistics",
        "paragraph_length_statistics",
        "length_paragraph_tokens",
        "text::length::paragraph_tokens_*",
        FeatureImplementationStatus.IMPLEMENTED,
        "paragraph token, character, syllable, and sentence-count summary statistics",
        InputLayer.PARAGRAPHS,
        TopicDependence.MIXED,
        "NaN when paragraph denominator is zero",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        57,
        "token, character, syllable, and sentence-count extended distribution-stat golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.vocabulary_size",
        "vocabulary_size",
        "counts",
        "text::counts::type_count",
        FeatureImplementationStatus.IMPLEMENTED,
        "count unique normalized token forms",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "defined as zero when token layer exists and is empty",
        "scalar",
        FeatureOutputMode.SCALAR,
        1,
        "golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.type_token_ratio",
        "type_token_ratio",
        "lexical_richness_ttr",
        "text::lexical_richness::ttr",
        FeatureImplementationStatus.IMPLEMENTED,
        "types divided by tokens",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        1,
        "golden and undefined tests present",
        "none",
    ),
    _deterministic_entry(
        "det.ttr_variants",
        "ttr_variants",
        "lexical_richness_variants",
        "text::lexical_richness::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "CTTR, Herdan C, MSTTR, MATTR, MTLD, HD-D, deterministic sampled model-fit vocd-D, and approximate vocd-D-fast",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "formula-specific NaN for zero or unstable denominators",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        8,
        "golden, undefined, true vocd-D sampling/model-fitting, vocd-D-fast, and formula page tests present",
        "none",
    ),
    _deterministic_entry(
        "det.hapax_legomena",
        "hapax_legomena",
        "lexical_richness_hapax",
        "text::lexical_richness_spectrum::hapax::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count types occurring exactly once and emit ratios over types, tokens, and per 1,000 tokens",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "counts are defined as zero when token layer exists; ratios are NaN when token or type denominators are zero",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        5,
        "legacy count and spectrum ratio golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.dis_legomena_frequency_spectrum",
        "dis_legomena_frequency_spectrum",
        "lexical_richness_frequency_spectrum",
        "text::lexical_richness_spectrum::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count types occurring exactly twice, emit ratios, and derive frequency spectrum V_i bins",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "counts are defined as zero when token layer exists; ratios are NaN when token or type denominators are zero",
        "fixed scalar set plus structured sidecar",
        FeatureOutputMode.SCALAR,
        65,
        "legacy count, dis ratios, V_i bins, and full-spectrum sidecar tests present",
        "frequency_spectrum_v1",
    ),
    _deterministic_entry(
        "det.yules_k",
        "yules_k",
        "lexical_richness_yules_k",
        "text::lexical_richness::yules_k",
        FeatureImplementationStatus.IMPLEMENTED,
        "10000 * (sum(i^2 * V_i) - N) / N^2",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        1,
        "golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.honore_r",
        "honore_r",
        "lexical_richness_honore_r",
        "text::lexical_richness::honore_r",
        FeatureImplementationStatus.IMPLEMENTED,
        "100 * log(N) / (1 - V1 / V)",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN for insufficient tokens, zero types, or all-hapax singularity",
        "scalar",
        FeatureOutputMode.SCALAR,
        1,
        "golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.guiraud_r",
        "guiraud_r",
        "lexical_richness_guiraud_r",
        "text::lexical_richness::guiraud_r",
        FeatureImplementationStatus.IMPLEMENTED,
        "V / sqrt(N)",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        1,
        "golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.sichel_simpson_renyi",
        "sichel_simpson_renyi",
        "lexical_richness_sichel_simpson_renyi",
        "text::lexical_richness::{sichel_s,simpson_d,renyi_entropy_alpha_2}",
        FeatureImplementationStatus.IMPLEMENTED,
        "frequency-spectrum formulas for Sichel S, Simpson D, and Renyi entropy alpha 2",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "formula-specific NaN for zero types, insufficient token pairs, or zero probability mass",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        3,
        "golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.lexical_density_by_lexicon",
        "lexical_density_by_lexicon",
        "lexical_density",
        "text::lexical_density::*",
        FeatureImplementationStatus.PARTIAL,
        "count alphabetic non-stopword tokens over total tokens",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        1,
        "aggregate golden tests present; versioned content lexicons pending",
        "none",
    ),
    _deterministic_entry(
        "det.lexical_sophistication_frequency_bands",
        "lexical_sophistication_frequency_bands",
        "lexical_sophistication_profile",
        "text::lexical_sophistication_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count token and type mass across versioned reference-frequency bands plus out-of-reference vocabulary with sidecar records",
        InputLayer.TOKENS,
        TopicDependence.TOPIC_SENSITIVE,
        "counts are defined as zero; token ratios are NaN when tokens are absent; type ratios are NaN when types are absent",
        "versioned seed frequency-band resource plus per-document frequency-band sidecar",
        FeatureOutputMode.SCALAR,
        20,
        "reference-list provenance, frequency-band golden, sidecar, diagnostics, output mode, and serialization tests present",
        "lexical_sophistication_frequency_bands_v1",
    ),
    _deterministic_entry(
        "det.stopword_ratios",
        "stopword_ratios",
        "closed_class_stopword",
        "text::stopword::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count stopword lexicon hits and grouped categories; emit raw counts and per-1,000-token rates",
        InputLayer.TOKENS,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "NaN when token denominator is zero",
        "fixed dense vector plus scalar summary",
        FeatureOutputMode.SCALAR,
        147,
        "aggregate and per-item/grouped golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.pronoun_usage",
        "pronoun_usage",
        "stance_pronoun",
        "text::pronoun::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count pronoun lexicon items and grouped person/number/case categories; emit raw counts and per-1,000-token rates",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "fixed dense vector plus scalar summary",
        FeatureOutputMode.SCALAR,
        67,
        "aggregate and per-item/grouped golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.person_ratios",
        "person_ratios",
        "stance_person",
        "text::stance::{first_person_ratio,second_person_ratio,third_person_ratio}",
        FeatureImplementationStatus.PARTIAL,
        "count first-, second-, and third-person pronouns over total tokens",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        3,
        "aggregate golden tests present; grouped metadata pending",
        "none",
    ),
    _deterministic_entry(
        "det.modal_verb_usage",
        "modal_verb_usage",
        "stance_modal",
        "text::modal::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count modal verb lexicon items and grouped modality categories; emit raw counts and per-1,000-token rates",
        InputLayer.TOKENS,
        TopicDependence.MIXED,
        "NaN when token denominator is zero",
        "fixed dense vector plus scalar summary",
        FeatureOutputMode.SCALAR,
        27,
        "aggregate and per-item/grouped golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.auxiliary_verb_usage",
        "auxiliary_verb_usage",
        "grammar_auxiliary",
        "text::auxiliary::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count auxiliary verb lexicon items and grouped auxiliary categories; emit raw counts and per-1,000-token rates",
        InputLayer.TOKENS,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "NaN when token denominator is zero",
        "fixed dense vector plus scalar summary",
        FeatureOutputMode.SCALAR,
        37,
        "aggregate and per-item/grouped golden tests present",
        "none",
    ),
    _deterministic_entry(
        "det.contraction_usage",
        "contraction_usage",
        "register_contraction",
        "text::contraction::*",
        FeatureImplementationStatus.IMPLEMENTED,
        (
            "count contraction lexicon items and grouped contraction categories; emit raw counts, "
            "per-1,000-token rates, and expansion sidecars"
        ),
        InputLayer.ORTHOGRAPHIC_TOKENS,
        TopicDependence.MIXED,
        "counts are zero when contractions are absent; rates are NaN when token denominator is zero; ambiguous expansions emit warnings",
        "fixed dense vector plus structured expansion sidecar",
        FeatureOutputMode.SCALAR,
        43,
        "aggregate, per-item/grouped, expansion sidecar, ambiguity diagnostic, output mode, and serialization tests present",
        "contraction_expansion_v1",
    ),
    _deterministic_entry(
        "det.punctuation_frequencies",
        "punctuation_frequencies",
        "punctuation_profile",
        "text::punctuation_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        (
            "count fixed punctuation marks, punctuation classes, and sentence-final punctuation categories; "
            "emit raw counts plus per-1,000-token and per-sentence rates"
        ),
        InputLayer.RAW,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "NaN when alphabetic, token, or sentence denominators are zero; raw counts are valid zeroes",
        "fixed dense vector plus legacy punctuation frequency vector, scalar summaries, and punctuation sidecar",
        FeatureOutputMode.DENSE_VECTOR,
        110,
        "fixed punctuation inventory, class, rate, sentence-final, sidecar, and legacy ASCII punctuation tests present",
        "punctuation_profile_sidecar_v1",
    ),
    _deterministic_entry(
        "det.punctuation_sequence_patterns",
        "punctuation_sequence_patterns",
        "orthography_punctuation_sequence",
        "text::orthography::punctuation_sequence_count; text::punctuation_ngram::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count repeated punctuation sequences, summarize repeated-sequence lengths, and fit Unicode punctuation n-grams",
        InputLayer.RAW,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "defined as zero when repeated sequences or fitted punctuation grams are absent",
        "scalar plus fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        65,
        "aggregate, repeated-sequence extended distribution, fitted punctuation n-gram, output mode, and serialization tests present",
        "none",
    ),
    _deterministic_entry(
        "det.capitalization_habits",
        "capitalization_habits",
        "orthography_capitalization",
        "text::capitalization_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        (
            "count uppercase characters, all-caps tokens, titlecase lines, camelCase, PascalCase, "
            "lowercase headings, and sentence-initial casing"
        ),
        InputLayer.RAW,
        TopicDependence.MIXED,
        "NaN when letter, token, line, or sentence-initial denominators are zero",
        "fixed scalar set plus capitalization profile",
        FeatureOutputMode.SCALAR,
        19,
        "aggregate, camel/Pascal, acronym-like, titlecase, lowercase-heading, and sentence-initial tests present",
        "none",
    ),
    _deterministic_entry(
        "det.spelling_variants",
        "spelling_variants",
        "orthography_spelling_variant",
        "text::spelling_variant_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count resource-backed spelling variant pairs with lowercase-normalized and exact-case outputs",
        InputLayer.TOKENS,
        TopicDependence.TOPIC_SENSITIVE,
        "counts are defined as zero; rates are NaN when tokens are absent; pair shares are NaN when pair is absent",
        "fixed scalar set plus legacy aggregate",
        FeatureOutputMode.SCALAR,
        36,
        "aggregate, versioned resource, per-pair, exact-case, diagnostics, output mode, and serialization tests present",
        "none",
    ),
    _deterministic_entry(
        "det.hyphenation_patterns",
        "hyphenation_patterns",
        "orthography_hyphenation",
        "text::hyphenation_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count hyphenated compounds, hyphenation classes, and fixed hyphenated-vs-solid variant pairs",
        InputLayer.ORTHOGRAPHIC_TOKENS,
        TopicDependence.MIXED,
        "counts are defined as zero; rates are NaN when orthographic tokens are absent; variant shares are NaN when pair is absent",
        "fixed scalar set plus legacy aggregate",
        FeatureOutputMode.SCALAR,
        23,
        "aggregate, hyphenation class, variant-pair, diagnostics, output mode, and serialization tests present",
        "none",
    ),
    _deterministic_entry(
        "det.abbreviation_acronym_patterns",
        "abbreviation_acronym_patterns",
        "orthography_abbreviation_acronym",
        "text::orthography::{abbreviation_count,acronym_count}; text::abbreviation_acronym_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count resource-backed abbreviation items/groups, named acronym items/groups, and deterministic acronym classes",
        InputLayer.RAW,
        TopicDependence.MIXED,
        "counts are defined as zero; rates are NaN when tokens are absent",
        "fixed scalar set plus versioned abbreviation and acronym resources, built-in acronym regex rules, and matched-span sidecar",
        FeatureOutputMode.SCALAR,
        82,
        (
            "aggregate, versioned resource, per-item/grouped abbreviation, named acronym, acronym class, sidecar, diagnostics, "
            "output mode tests present"
        ),
        "abbreviation_acronym_matches_v2",
    ),
    _deterministic_entry(
        "det.quote_dialogue_markers",
        "quote_dialogue_markers",
        "discourse_quote_dialogue",
        "text::discourse::{quote_marker_count,dialogue_dash_count}; text::quote_dialogue_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count quote mark subtypes, apostrophes, quote spans, nested quotes, block quotes, dialogue dashes, and speaker tags",
        InputLayer.RAW,
        TopicDependence.MIXED,
        "counts are defined as zero; rates are NaN when tokens are absent",
        "fixed scalar set plus built-in quote/dialogue profile rules and attribution sidecar",
        FeatureOutputMode.SCALAR,
        22,
        "aggregate, quote subtype, apostrophe, nested quote, block quote, dialogue dash, speaker-tag, sidecar, diagnostics tests present",
        "quote_dialogue_attribution_v1",
    ),
    _deterministic_entry(
        "det.discourse_marker_frequencies",
        "discourse_marker_frequencies",
        "discourse_marker",
        "text::discourse::discourse_marker_count; text::discourse_marker_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count resource-backed discourse marker items and grouped marker categories",
        InputLayer.RAW,
        TopicDependence.MIXED,
        "counts are defined as zero; rates are NaN when tokens are absent",
        "fixed scalar set plus versioned discourse marker resource and matched-span sidecar",
        FeatureOutputMode.SCALAR,
        31,
        "aggregate, versioned resource, per-marker, grouped, sidecar, polyfunctional diagnostics, and output mode tests present",
        "discourse_marker_profile_matches_v1",
    ),
    _deterministic_entry(
        "det.transition_phrase_frequencies",
        "transition_phrase_frequencies",
        "transition_phrase",
        "text::discourse::transition_phrase_count; text::transition_phrase_profile::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count resource-backed transition phrase items and grouped transition categories",
        InputLayer.RAW,
        TopicDependence.MIXED,
        "counts are defined as zero; rates are NaN when tokens are absent",
        "fixed scalar set plus versioned transition phrase resource and matched-span sidecar",
        FeatureOutputMode.SCALAR,
        23,
        "aggregate, versioned resource, per-phrase, grouped, sidecar, diagnostics, and output mode tests present",
        "transition_phrase_profile_matches_v1",
    ),
    _deterministic_entry(
        "det.formatting_layout_features",
        "formatting_layout_features",
        "layout",
        "text::layout::*; text::layout_whitespace_profile::layout_marker=*; text::layout_whitespace_profile::section_depth::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count legacy layout scalars, layout marker classes, and Markdown section-depth features",
        InputLayer.RAW,
        TopicDependence.MIXED,
        "counts are zero; line-normalized rates are NaN without lines; mean heading depth is NaN without headings",
        "fixed scalar set plus built-in layout/whitespace profile rules and layout marker sidecar",
        FeatureOutputMode.SCALAR,
        23,
        "aggregate, layout marker, section depth, sidecar, diagnostics, output mode, and serialization tests present",
        "layout_marker_sidecar_v1",
    ),
    _deterministic_entry(
        "det.whitespace_line_break_habits",
        "whitespace_line_break_habits",
        "whitespace",
        "text::whitespace::*; text::layout_whitespace_profile::whitespace=*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count blank lines, line breaks, indentation, tabs, repeated spaces, leading/trailing whitespace, and hard-wrap indicators",
        InputLayer.RAW,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "counts are zero; line-normalized rates are NaN without lines; mean indentation is NaN without nonblank lines",
        "fixed scalar set, line-length distribution stats, and built-in layout/whitespace profile rules",
        FeatureOutputMode.SCALAR,
        36,
        "aggregate, line-length extended distribution, indentation, tab, repeated-space, trailing-space, wrapping tests present",
        "none",
    ),
    _deterministic_entry(
        "det.readability_explicit_formula",
        "readability_explicit_formula",
        "readability",
        "text::readability::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "Flesch, Flesch-Kincaid, Gunning Fog, Coleman-Liau, SMOG, ARI, Dale-Chall, FORCAST, Linsear Write, and LIX",
        InputLayer.MULTI,
        TopicDependence.MIXED,
        "formula-specific NaN for zero denominators and sample-size gates; short text emits diagnostics",
        "fixed scalar set plus project-owned Dale-Chall seed easy-word resource",
        FeatureOutputMode.SCALAR,
        10,
        "golden formula, short-threshold diagnostics, output mode, serialization, and formula page tests present",
        "none",
    ),
)


_OTHER_NON_LLM_ENTRIES = (
    _other_entry(
        "nonllm.pos_tag_frequencies",
        "pos_tag_frequencies",
        "parser_pos_frequency",
        "text::syntax::pos_frequency::upos=*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count Universal POS tags from configured fake parser fixture divided by parsed token count",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; NaN when parser token denominator is zero",
        "generated dense or sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, output mode, serialization, missing-layer, and zero-token diagnostic tests present",
        17,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.pos_ngrams",
        "pos_ngrams",
        "parser_pos_ngram",
        "text::syntax::pos_ngram::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "sliding contiguous Universal POS n-grams over configured fake parser fixtures with deterministic fitted vocabulary",
        InputLayer.NLP,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "requires parser layer; defined after fit; absent fitted grams are valid zeros",
        "fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, fitted-vocabulary, output mode, serialization, missing-layer, "
        "and empty-vocabulary tests present",
        0,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.pos_skipgrams",
        "pos_skipgrams",
        "parser_pos_skipgram",
        "text::syntax::pos_skipgram::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "non-contiguous Universal POS skip-bigrams over configured fake parser fixtures with deterministic fitted vocabulary",
        InputLayer.NLP,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "requires parser layer; defined after fit; absent fitted skip-grams are valid zeros",
        "fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, fitted-vocabulary, output mode, serialization, missing-layer, "
        "and empty-vocabulary tests present",
        0,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.morphological_feature_frequencies",
        "morphological_feature_frequencies",
        "parser_morphology_frequency",
        "text::syntax::morphology_frequency::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count fitted Universal Dependencies morphology attribute/value observations over configured fake parser fixtures",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; defined after fit; absent fitted morphology attributes are valid zeros",
        "fitted dense or sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, fitted-vocabulary, output mode, serialization, missing-layer, "
        "and empty-vocabulary tests present",
        0,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.dependency_relation_frequencies",
        "dependency_relation_frequencies",
        "parser_dependency_relation_frequency",
        "text::syntax::dependency_relation_frequency::deprel=*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count Universal Dependencies basic relation labels from configured fake parser fixture divided by dependency arc count",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; NaN when dependency arc denominator is zero",
        "generated dense or sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, output mode, serialization, missing-layer, and zero-arc diagnostic tests present",
        37,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.dependency_ngrams_dtgrams_subtrees",
        "dependency_ngrams_dtgrams_subtrees",
        "parser_dependency_structures",
        "text::syntax::{dependency_ngram,dependency_path,dependency_subtree,dependency_dtgram}::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "extract fitted dependency paths, n-grams, subtrees, and DT-grams over configured fake parser fixtures",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; defined after fit; absent fitted dependency structures are valid zeros",
        "fitted sparse vector",
        FeatureOutputMode.SPARSE_VECTOR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, fitted-vocabulary, output mode, serialization, missing-layer, "
        "and empty-vocabulary tests present",
        0,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.dependency_distance",
        "dependency_distance",
        "parser_dependency_distance_root_statistics",
        "text::syntax::{dependency_distance_*,root_statistics::*}",
        FeatureImplementationStatus.IMPLEMENTED,
        "compute head-dependent token distance distribution statistics and root node statistics over configured fake parser fixtures",
        InputLayer.NLP,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "requires parser layer; dependency-distance count is zero without non-root arcs; other distance statistics are NaN when undefined",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden distance/root-statistic, output mode, serialization, missing-layer, "
        "and undefined-diagnostic tests present",
        33,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.parse_tree_depth",
        "parse_tree_depth",
        "parser_parse_depth",
        "text::syntax::parse_depth_*",
        FeatureImplementationStatus.IMPLEMENTED,
        "compute dependency tree edge-depth distribution statistics over configured fake parser fixtures",
        InputLayer.NLP,
        TopicDependence.MOSTLY_TOPIC_INDEPENDENT,
        "requires parser layer; parse-depth count is zero without dependency arcs; other depth statistics are NaN when undefined",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden parse-depth, output mode, serialization, missing-layer, cycle, "
        "and undefined-diagnostic tests present",
        14,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.syntactic_complexity_metrics",
        "syntactic_complexity_metrics",
        "parser_syntactic_complexity",
        "text::syntax::syntactic_complexity::*",
        FeatureImplementationStatus.IMPLEMENTED,
        "compute MLS, MLT, MLC, C/S, C/T, CP/T, DC/C, CN/C, CN/T, VP/T, and T/S over configured fake syntactic-count annotations",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer and clause/T-unit rules; ratio features are NaN when their denominator is zero",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, output mode, serialization, missing-layer, invalid-count, "
        "and undefined-diagnostic tests present",
        11,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.clause_counts",
        "clause_counts",
        "parser_clause_count",
        "text::syntax::{clause_count,t_unit_count}",
        FeatureImplementationStatus.IMPLEMENTED,
        "emit parser-derived clause and T-unit counts from configured fake syntactic-count annotations",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; zero counts are valid",
        "fixed scalar set",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, output mode, serialization, missing-layer, and invalid-count tests present",
        2,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.subordination_metrics",
        "subordination_metrics",
        "parser_subordination",
        "text::syntax::subordination_ratio",
        FeatureImplementationStatus.IMPLEMENTED,
        "count dependent clauses over clauses from configured fake syntactic-count annotations",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; NaN when clause_count denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, output mode, serialization, missing-layer, and undefined-diagnostic tests present",
        1,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.coordination_metrics",
        "coordination_metrics",
        "parser_coordination",
        "text::syntax::coordination_ratio",
        FeatureImplementationStatus.IMPLEMENTED,
        "count coordinate phrases over T-units from configured fake syntactic-count annotations",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; NaN when t_unit_count denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, output mode, serialization, missing-layer, and undefined-diagnostic tests present",
        1,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.passive_voice_frequency",
        "passive_voice_frequency",
        "parser_passive_voice",
        "text::syntax::passive_voice_frequency",
        FeatureImplementationStatus.IMPLEMENTED,
        "detect strict fake-parser passive voice constructions from Voice=Pass morphology plus aux:pass and nsubj:pass dependents",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer and syntactic-count annotations; NaN when clause_count denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, copular/adjectival false-positive, output mode, serialization, "
        "missing-layer, and zero-clause diagnostic tests present",
        1,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.lexical_density_by_pos",
        "lexical_density_by_pos",
        "parser_pos_lexical_density",
        "text::syntax::pos_lexical_density",
        FeatureImplementationStatus.IMPLEMENTED,
        "count Universal POS ADJ, ADV, NOUN, and VERB tokens over all configured fake parser tokens",
        InputLayer.NLP,
        TopicDependence.MIXED,
        "requires parser layer; NaN when parser token denominator is zero",
        "scalar",
        FeatureOutputMode.SCALAR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, output mode, serialization, missing-layer, and zero-token diagnostic tests present",
        1,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.named_entity_density",
        "named_entity_density",
        "parser_named_entity_density",
        "text::{style_adjacent,content_control}::named_entity_density::entity_type=*",
        FeatureImplementationStatus.IMPLEMENTED,
        "count configured fake named-entity labels by type as style-adjacent and topic-control density outputs",
        InputLayer.NLP,
        TopicDependence.TOPIC_SENSITIVE,
        "requires parser or NER layer; NaN when parser token denominator is zero",
        "configured dense vector",
        FeatureOutputMode.DENSE_VECTOR,
        "core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.features.optional",
        "fail-fast catalog, fake-provider golden, style-adjacent/topic-control output, output mode, serialization, "
        "missing-layer, invalid-label, invalid-span, and zero-token diagnostic tests present",
        0,
        "parser_metadata",
    ),
    _other_entry(
        "nonllm.content_masking_topic_neutral_distortion",
        "content_masking_topic_neutral_distortion",
        "content_masking",
        "text::content_control::{content_masking::masked_text,topic_neutral_distortion::masked_token_ratio}",
        FeatureImplementationStatus.IMPLEMENTED,
        "replace configured content words or parser/NER content tokens with placeholders and emit masked-token distortion ratio",
        InputLayer.MULTI,
        TopicDependence.TOPIC_CONTROL,
        (
            "requires valid mask token and content-word inventory or fake parser/NER annotations; "
            "parser ratio is NaN when token denominator is zero"
        ),
        "structured transformed text plus scalar ratio",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "core; core fake-provider; parser-spacy and parser-stanza adapters present",
        "stylometry_python_lib.evaluation",
        "content masking utility tests plus parser-backed fake-provider golden, sidecar, output mode, serialization, missing-layer, "
        "invalid-config, invalid-span, and zero-token diagnostic tests present",
        1,
        "parser_content_masking_v1",
    ),
    _other_entry(
        "nonllm.topic_modeling_prediction_controls",
        "topic_modeling_prediction_controls",
        "topic_prediction_leakage",
        "evaluation::{topic_prediction_leakage_score,topic_prediction_control_report,TopicPredictionControl,topic_model_report}",
        FeatureImplementationStatus.IMPLEMENTED,
        "fit topic classifier protocol and report leakage score plus structured cross-validation diagnostics",
        InputLayer.MULTI,
        TopicDependence.TOPIC_CONTROL,
        "requires aligned feature rows and topic labels",
        "scalar and structured classifier report",
        FeatureOutputMode.SCALAR,
        "core",
        "stylometry_python_lib.evaluation",
        "leakage utility, classifier-control protocol, and LDA/NMF topic-model tests present",
        1,
        "evaluation_diagnostics",
    ),
    _other_entry(
        "nonllm.standardization_z_scores",
        "standardization_z_scores",
        "z_score_standardizer",
        "evaluation::z_score",
        FeatureImplementationStatus.IMPLEMENTED,
        "standardize columns by corpus mean and standard deviation",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires non-empty numeric matrix and configured zero-variance policy",
        "dense matrix",
        FeatureOutputMode.DENSE_VECTOR,
        "core",
        "stylometry_python_lib.evaluation",
        "utility tests present",
        0,
        "none",
    ),
    _other_entry(
        "nonllm.pca_dimensionality_reduction",
        "pca_dimensionality_reduction",
        "pca_reducer",
        "evaluation::pca_reducer",
        FeatureImplementationStatus.IMPLEMENTED,
        "PCA or SVD-style reduction over numeric feature matrix",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires valid numeric matrix and component count",
        "dense matrix",
        FeatureOutputMode.DENSE_VECTOR,
        "core",
        "stylometry_python_lib.evaluation",
        "PCA and direct SVD tests present",
        0,
        "none",
    ),
    _other_entry(
        "nonllm.burrows_delta_distance_metrics",
        "burrows_delta_distance_metrics",
        "distance_metrics",
        "evaluation::{burrows_delta,cosine_distance,euclidean_distance}",
        FeatureImplementationStatus.IMPLEMENTED,
        "compute Burrows Delta, cosine distance, and Euclidean distance matrices",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires numeric matrix with non-zero norms where applicable",
        "pairwise matrix",
        FeatureOutputMode.PAIRWISE_MATRIX,
        "core",
        "stylometry_python_lib.evaluation",
        "distance tests present",
        0,
        "none",
    ),
    _other_entry(
        "nonllm.clustering_pca_visualizations",
        "clustering_pca_visualizations",
        "clustering_visualization",
        "evaluation::{cluster_feature_matrix,tsne_embedding,umap_embedding}",
        FeatureImplementationStatus.IMPLEMENTED,
        "cluster feature vectors and project to low dimensions for visualization; rendering left to the caller",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires enough samples for selected clustering method",
        "labels, distances, and low-dimensional projection arrays",
        FeatureOutputMode.PANDAS_DIAGNOSTIC,
        "core t-SNE; umap-learn optional extra",
        "stylometry_python_lib.evaluation",
        "k-means label/distance, t-SNE, and UMAP projection tests present",
        0,
        "clustering_result",
    ),
    _other_entry(
        "nonllm.supervised_classifiers",
        "supervised_classifiers",
        "classifier_wrappers",
        "evaluation::{SupervisedClassifier,classifier_report}",
        FeatureImplementationStatus.IMPLEMENTED,
        "fit explicit classifier wrappers for author attribution evaluation tasks",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires aligned labels and sufficient class counts",
        "estimator outputs",
        FeatureOutputMode.DENSE_VECTOR,
        "core",
        "stylometry_python_lib.evaluation",
        "logistic regression, linear SVM, random forest, and nearest-centroid wrapper tests present",
        0,
        "classification_report",
    ),
    _other_entry(
        "nonllm.open_world_verification_models",
        "open_world_verification_models",
        "open_world_verification",
        "evaluation::{thresholded_distance_verification,one_class_verification,calibrated_binary_verification}",
        FeatureImplementationStatus.IMPLEMENTED,
        "thresholded distance, one-class, and calibrated binary verification protocols",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires preserved document identity mappings",
        "pairwise decisions",
        FeatureOutputMode.PAIRWISE_MATRIX,
        "core",
        "stylometry_python_lib.evaluation",
        "thresholded Euclidean/cosine, one-class, and calibrated binary verification tests present",
        0,
        "verification_report",
    ),
    _other_entry(
        "nonllm.shap_feature_importance",
        "shap_feature_importance",
        "feature_importance",
        "evaluation::{permutation_importance_report,shap_importance_report}",
        FeatureImplementationStatus.IMPLEMENTED,
        "permutation importance first; SHAP behind optional extra",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires fitted estimator and labeled data",
        "importance table",
        FeatureOutputMode.PANDAS_DIAGNOSTIC,
        "core; shap optional extra",
        "stylometry_python_lib.evaluation",
        "permutation-importance tests present; SHAP optional-extra tests present",
        0,
        "importance_report",
    ),
    _other_entry(
        "nonllm.cross_topic_evaluation",
        "cross_topic_evaluation",
        "cross_topic_holdout",
        "evaluation::cross_topic_holdout",
        FeatureImplementationStatus.IMPLEMENTED,
        "train/test split by held-out topic label",
        InputLayer.MULTI,
        TopicDependence.TOPIC_CONTROL,
        "requires topic labels and requested held-out topic",
        "index vectors",
        FeatureOutputMode.DENSE_VECTOR,
        "core",
        "stylometry_python_lib.evaluation",
        "split tests present; underpowered diagnostics pending",
        0,
        "split_diagnostics",
    ),
    _other_entry(
        "nonllm.same_topic_hard_negatives",
        "same_topic_hard_negatives",
        "same_topic_hard_negatives",
        "evaluation::same_topic_hard_negative_pairs",
        FeatureImplementationStatus.IMPLEMENTED,
        "generate same-topic different-author hard-negative pairs",
        InputLayer.MULTI,
        TopicDependence.TOPIC_CONTROL,
        "requires aligned author and topic labels",
        "pair indices",
        FeatureOutputMode.PAIRWISE_MATRIX,
        "core",
        "stylometry_python_lib.evaluation",
        "pair tests present; insufficiency diagnostics pending",
        0,
        "pair_diagnostics",
    ),
    _other_entry(
        "nonllm.two_way_anova",
        "two_way_anova",
        "author_topic_effects",
        "evaluation::{two_way_effect_sizes,two_way_anova_report}",
        FeatureImplementationStatus.IMPLEMENTED,
        "rough author/topic effect-size analysis plus full two-way ANOVA with p-values and interaction",
        InputLayer.MULTI,
        TopicDependence.TOPIC_CONTROL,
        "requires aligned author and topic labels",
        "effect-size report",
        FeatureOutputMode.PANDAS_DIAGNOSTIC,
        "core; statsmodels optional extra",
        "stylometry_python_lib.evaluation",
        "effect-size tests present; statsmodels p-value/interaction tests present",
        0,
        "anova_report",
    ),
    _other_entry(
        "nonllm.ablation_studies",
        "ablation_studies",
        "feature_family_ablation",
        "evaluation::ablation_scores",
        FeatureImplementationStatus.IMPLEMENTED,
        "score configured feature-family subsets with caller-provided scoring function",
        InputLayer.MULTI,
        TopicDependence.TOPIC_CONTROL,
        "requires aligned labels and feature families",
        "score mapping",
        FeatureOutputMode.PANDAS_DIAGNOSTIC,
        "core",
        "stylometry_python_lib.evaluation",
        "ablation tests present",
        0,
        "none",
    ),
    _other_entry(
        "nonllm.human_expert_validation",
        "human_expert_validation",
        "human_review_packet",
        "evaluation::{human_review_packet,human_review_packet_to_json,human_review_packet_to_csv}",
        FeatureImplementationStatus.IMPLEMENTED,
        "build structured review packets for human forensic or stylistic expert review",
        InputLayer.MULTI,
        TopicDependence.NOT_APPLICABLE,
        "requires selected features and document metadata",
        "review artifact",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "core",
        "stylometry_python_lib.evaluation",
        "structured packet tests and JSON/CSV exporter tests present",
        0,
        "human_review_packet_v1",
    ),
)


_LLM_ENTRIES = (
    _llm_entry(
        "llm.tone_classification",
        "tone_classification",
        "llm_tone",
        "text::llm::tone",
        "prompt LLM with fixed tone labels and validate JSON response",
        TopicDependence.MIXED,
        "scalar or structured label scores",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.register_formality",
        "register_formality",
        "llm_register",
        "text::llm::register",
        "prompt LLM with register/formality taxonomy and validate JSON response",
        TopicDependence.MIXED,
        "scalar or structured label scores",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.voice_persona_description",
        "voice_persona_description",
        "llm_persona",
        "text::llm::persona",
        "prompt for constrained authorial voice/persona descriptors",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.narrative_perspective",
        "narrative_perspective",
        "llm_narrative_perspective",
        "text::llm::narrative_perspective",
        "prompt for narrative perspective classification",
        TopicDependence.MIXED,
        "scalar or structured label scores",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.sentence_level_intent",
        "sentence_level_intent",
        "llm_sentence_intent",
        "text::llm::sentence_intent",
        "prompt per sentence with fixed speech-act labels",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.discourse_function_labels",
        "discourse_function_labels",
        "llm_discourse_function",
        "text::llm::discourse_function",
        "prompt with fixed discourse taxonomy",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.rhetorical_structure",
        "rhetorical_structure",
        "llm_rhetorical_structure",
        "text::llm::rhetorical_structure",
        "prompt for claim/evidence/counterargument and rhetoric schema",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.argumentation_style",
        "argumentation_style",
        "llm_argumentation_style",
        "text::llm::argumentation_style",
        "prompt with fixed argumentation style rubrics",
        TopicDependence.MIXED,
        "scalar or structured rubric scores",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.coherence_cohesion_judgments",
        "coherence_cohesion_judgments",
        "llm_cohesion_judgment",
        "text::llm::cohesion_judgment",
        "prompt for coherence and cohesion ratings with evidence schema",
        TopicDependence.MIXED,
        "scalar or structured rubric scores",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.topic_style_separation_judgments",
        "topic_style_separation_judgments",
        "llm_style_topic_separation",
        "text::llm::style_topic_separation",
        "pairwise prompt to separate topic similarity from style similarity",
        TopicDependence.TOPIC_CONTROL,
        "pairwise structured score",
        FeatureOutputMode.PAIRWISE_MATRIX,
        "llm_pairwise_annotation",
    ),
    _llm_entry(
        "llm.stylistic_similarity_judgments",
        "stylistic_similarity_judgments",
        "llm_stylistic_similarity",
        "text::llm::stylistic_similarity",
        "pairwise prompt for same-style or stylistic-distance estimate",
        TopicDependence.MIXED,
        "pairwise structured score",
        FeatureOutputMode.PAIRWISE_MATRIX,
        "llm_pairwise_annotation",
    ),
    _llm_entry(
        "llm.pairwise_comparison_features",
        "pairwise_comparison_features",
        "llm_pairwise_style_comparison",
        "text::llm::pairwise_style_comparison",
        "pairwise prompt for relative style preferences and comparison features",
        TopicDependence.MIXED,
        "pairwise structured score",
        FeatureOutputMode.PAIRWISE_MATRIX,
        "llm_pairwise_annotation",
    ),
    _llm_entry(
        "llm.stylistic_difference_explanations",
        "stylistic_difference_explanations",
        "llm_style_difference_explanation",
        "text::llm::style_difference_explanation",
        "pairwise prompt for evidence-backed stylistic difference explanation",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_explanation",
    ),
    _llm_entry(
        "llm.imitability_style_transfer_descriptors",
        "imitability_style_transfer_descriptors",
        "llm_style_transfer_descriptor",
        "text::llm::style_transfer_descriptor",
        "prompt for transferable style recipe descriptors",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.authorial_habit_summaries",
        "authorial_habit_summaries",
        "llm_authorial_habit_summary",
        "text::llm::authorial_habit_summary",
        "summarize recurrent style habits over multiple samples",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
    _llm_entry(
        "llm.prompt_derived_style_vectors",
        "prompt_derived_style_vectors",
        "llm_prompt_derived_vector",
        "text::llm::prompt_derived_vector",
        "derive vector representation from prompt-mediated style representation",
        TopicDependence.MIXED,
        "dense vector",
        FeatureOutputMode.DENSE_VECTOR,
        "llm_vector",
    ),
    _llm_entry(
        "llm.embeddings_style_similarity",
        "embeddings_style_similarity",
        "llm_embedding",
        "text::llm::embedding",
        "embed text and compare vector distances under topic-leakage controls",
        TopicDependence.TOPIC_SENSITIVE,
        "dense vector",
        FeatureOutputMode.DENSE_VECTOR,
        "llm_embedding",
    ),
    _llm_entry(
        "llm.style_tuned_contrastive_embeddings",
        "style_tuned_contrastive_embeddings",
        "llm_style_tuned_embedding",
        "text::llm::style_tuned_embedding",
        "accept or produce style-tuned/contrastive embeddings with provenance",
        TopicDependence.MIXED,
        "dense vector",
        FeatureOutputMode.DENSE_VECTOR,
        "llm_embedding",
    ),
    _llm_entry(
        "llm.same_author_prediction",
        "same_author_prediction",
        "llm_same_author_prediction",
        "text::llm::same_author_prediction",
        "prompt same/different author prediction for text pairs",
        TopicDependence.MIXED,
        "pairwise structured score",
        FeatureOutputMode.PAIRWISE_MATRIX,
        "llm_pairwise_annotation",
    ),
    _llm_entry(
        "llm.generated_feature_extraction",
        "generated_feature_extraction",
        "llm_generated_feature_extraction",
        "text::llm::generated_feature_extraction",
        "prompt for fixed JSON feature-extraction schema",
        TopicDependence.MIXED,
        "structured sidecar",
        FeatureOutputMode.STRUCTURED_SIDECAR,
        "llm_annotation",
    ),
)
